### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Lizzetee** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Lizzetee#1]
[Infografia leng. contratos inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Lizzetee/files/8692576/Infografia.leng.contratos.inteligentes.pdf)

**Comment by carlos-chrs** [comment]
muy bien...
20/20
calificado....

**Comment by josealfredo79** [comment]
Bien hecho y revisado
